# Generated by Django 5.2.3 on 2025-07-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='total_seats',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
